Repository board-together/FE-Board-Together, pull requests merged in 2023-02, with the labels that each got.

#4 Starter repo cleanup
  README.md
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: Thomas, FE

#5 Combined/feature/component architecture
  package-lock.json
  package.json
  src/App.js
  src/GraphQL/mutations.js
  src/GraphQL/queries.js
  src/components/App/App.js
  src/components/Friends_Games/Friends_Games.js
  src/components/Game_Modal/Game_Modal.js
  src/components/Login/Login.js
  src/components/Navbar/Navbar.js
  src/components/Search_Results/Search_Results.js
  src/components/User_Dashboard/User_Dashboard.js
  src/components/User_Games/User_Games.js
  src/index.js
Labels: FE

#6 Thomas/featured/navbar
  src/components/App/App.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Searchbar/Searchbar.css
  src/components/Searchbar/Searchbar.js
Labels: Thomas, UX/UI, FE

#7 Adds useReducer and refactors the app to search bar interaction
  cypress/e2e/navbar.spec.cy.js
  src/components/App/App.js
  src/components/Navbar/Navbar.js
  src/components/Search_Results/Search_Results.js
  src/components/Searchbar/Searchbar.js
  src/dummy_data.json
Labels: enhancement, Thomas, Spencer, FE

#8 Spencer/feature/user dashboard
  cypress/e2e/user_dashboad.cy.js
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Navbar/Navbar.js
  src/components/User_Dashboard/User_Dashboard.css
  src/components/User_Dashboard/User_Dashboard.js
  src/dummy_user_data.json
Labels: enhancement, Spencer

#9 Feature/single game
  cypress/e2e/search_results.spec.cy.js
  src/components/App/App.js
  src/components/Search_Results/Search_Results.js
  src/components/Searchbar/Searchbar.js
  src/components/Single_Game/Single_Game.css
  src/components/Single_Game/Single_Game.js
Labels: enhancement, Thomas, FE, Testing

#13 Installs apollo
  package-lock.json
  package.json
Labels: Thomas, FE, Set-Up

#17 Spencer/game cover styles
  cypress/e2e/user_dashboad.cy.js
  src/components/App/App.js
  src/components/Login/Login.js
  src/components/Navbar/Navbar.js
  src/components/Search_Results/Search_Results.js
  src/components/Searchbar/Searchbar.js
  src/components/Single_Game/Single_Game.css
  src/components/Single_Game/Single_Game.js
  src/components/User_Dashboard/User_Dashboard.css
  src/components/User_Dashboard/User_Dashboard.js
  src/dummy_data.json
  src/dummy_user_data.json
  src/index.js
Labels: UX/UI, Spencer, FE, Testing

#19 Fixes search bug
  src/components/App/App.js
  src/components/Login/Login.js
  src/components/Search_Results/Search_Results.js
  src/components/Searchbar/Searchbar.js
  src/components/Single_Game/Single_Game.js
Labels: fix

#27 Spencer/feature/modal
  cypress/e2e/login.cy.js
  cypress/e2e/modal.cy.js
  src/components/App/App.js
  src/components/Game_Modal/Game_Modal.css
  src/components/Game_Modal/Game_Modal.js
  src/components/Search_Results/Search_Results.js
  src/components/Single_Game/Single_Game.js
  src/components/User_Dashboard/User_Dashboard.js
Labels: enhancement, UX/UI, Spencer, FE

#29 Spencer/feature/modal
  cypress/e2e/modal.cy.js
  src/components/App/App.js
  src/components/Game_Modal/Game_Modal.css
  src/components/Game_Modal/Game_Modal.js
  src/components/Search_Results/Search_Results.js
  src/components/Single_Game/Single_Game.js
  src/components/User_Dashboard/User_Dashboard.js
Labels: enhancement, UX/UI, Spencer, FE, Testing

#24 Feature/thomas/friends games
  cypress/e2e/friends-games.spec.cy.js
  src/components/App/App.js
  src/components/Friends_Games/Friends_Games.css
  src/components/Friends_Games/Friends_Games.js
  src/components/Navbar/Navbar.css
  src/components/Single_Game/Single_Game.js
  src/components/User_Dashboard/User_Dashboard.js
Labels: enhancement, Thomas, FE, Testing

#44 Feature/search results gql
  cypress/e2e/search_results.spec.cy.js
  src/GraphQL/queries.js
  src/components/App/App.js
  src/components/Search_Results/Search_Results.css
  src/components/Search_Results/Search_Results.js
  src/components/Single_Game_Varient/SingleGameVarinet.js
  src/components/Single_Game_Varient/Single_Game_Varient.css
Labels: enhancement, Thomas, UX/UI, FE, fix

#47 Conditionally render buttons in modal depending on context
  src/GraphQL/queries.js
  src/apiCalls.js
  src/components/App/App.js
  src/components/Friends_Games/Friends_Games.js
  src/components/Game_Modal/Game_Modal.js
  src/components/Search_Results/Search_Results.css
  src/components/Search_Results/Search_Results.js
  src/components/Single_Game/Single_Game.js
  src/components/Single_Game_Varient/SingleGameVarinet.js
  src/utils.js
Labels: enhancement, Spencer, FE

#53 Feat/thomas/add game to colection
  cypress/e2e/friends-games.spec.cy.js
  cypress/e2e/login.cy.js
  cypress/e2e/modal.cy.js
  cypress/e2e/navbar.spec.cy.js
  cypress/e2e/search_results.spec.cy.js
  cypress/e2e/user_dashboad.cy.js
  src/GraphQL/mutations.js
  src/GraphQL/queries.js
  src/components/App/App.js
  src/components/Game_Modal/Game_Modal.js
  src/components/Search_Results/Search_Results.js
  src/components/Single_Game/Single_Game.css
  src/components/Single_Game/Single_Game.js
  src/components/User_Dashboard/User_Dashboard.css
  src/components/User_Dashboard/User_Dashboard.js
  src/dummy-borrowed-games.json
  src/dummy_data.json
  src/dummy_user_data.json
Labels: enhancement, Thomas, UX/UI, FE, Testing

#59 Testing/refactor/add game
  cypress/e2e/adding_game.spec.cy.js
  cypress/e2e/search_results.spec.cy.js
  cypress/fixtures/search_games.json
Labels: FE, Testing

#65 Feat/thomas/error component
  public/board-game.png
  public/index.html
  src/components/App/App.js
  src/components/ErrorPage/Error_Page.css
  src/components/ErrorPage/Error_Page.js
  src/components/Search_Results/Search_Results.js
Labels: enhancement
